### ISSUE TITLE
Add Help Request menu to nav bar

### ISSUE THREAD

**Issue by notkevin12** [ucsb-cs156-s22/team03-s22-6pm-1#19]
- [x] There is a button labeled Help Request on the nav bar for logged in users.
- [x] By clicking on the button, a dropdown menu with only one entry labeled list help request appears.
- [x] By clicking on the entry labeled list help request, users go to helprequest/list which shows the table of help requests in the database.
- [x] The Help Request button is 100% covered by the test cases and mutation tests.
- [x] The new changes are updated to Heroku depolyment .

**Comment by hanzemeng** [comment]
- [x] There is a button labeled Help Request on the nav bar for logged in users.
- [x] By clicking on the button, the user goes to a page that lists all help requests in the database.
- [x] The Help Request button is 100% covered by the test cases and mutation tests.
- [x] The new changes are updated to Heroku depolyment .
