### ISSUE TITLE
Add Placeholder for Help Request Index Page

### ISSUE THREAD

**Issue by notkevin12** [ucsb-cs156-s22/team03-s22-6pm-1#20]
- [x] The users sees a placeholder page for help request data after clicked on the corrisponding button on the nav bar.
- [x] The page is titled Help Request and mentions that this is just a placeholder for the actual index page. 
- [x] The placeholder page can be seen on Heroku depolyment.
- [x] The upadte has 100% test coverage and mutation test coverage.

**Comment by hanzemeng** [comment]
- [x] The users sees a placeholder page for help request data after clicked on the corrisponding button on the nav bar.
- [x] The placeholder page can be seen on Heroku depolyment.
- [x] The upadte has 100% test coverage and mutation test coverage.
