### ISSUE TITLE
Add HelpRequestTable component to Storybook (along with fixtures)

### ISSUE THREAD

**Issue by notkevin12** [ucsb-cs156-s22/team03-s22-6pm-1#21]
- [x] The storybook shows an empty table of help request, and a table of three help requests.
- [x] Each column of the table shows the correct field of help request.
- [x] There are three fixtures of help requests in the source code.
- [x] Every fixture has all of the fields defined in Help Request and each field has a reasonable/expected value.
- [x] 100% test coverage and mutation coverage.

**Comment by hanzemeng** [comment]
- [x] The storybook shows a table of help requests.
- [x] There are three fixtures of help requests in the source code.
- [x] 100% test coverage and mutation coverage.
