### ISSUE TITLE
Replace HelpRequestTable placeholder page with one that includes Help Request Table

### ISSUE THREAD

**Issue by notkevin12** [ucsb-cs156-s22/team03-s22-6pm-1#22]
- [x] The placeholder page has been replaced with a table that shows Help Requests in the database.
- [x] Each column of the table shows the correct field of help request.
- [x] Each row of the table shows the correct information of each help request.
- [x] Logged in user can see the new table on Heroku depolyment by clicking on the help request button on the nav bar.
- [x] 100% test coverage and mutation coverage.

**Comment by hanzemeng** [comment]
- [x] The placeholder page has been replaced with a table that shows Help Requests in the database.
- [x] Logged in user can see the new table on Heroku depolyment by clicking on the help request button on the nav bar.
- [x] 100% test coverage and mutation coverage.
