### ISSUE TITLE
Add Delete Column to HelpRequestTable (if not already done)

### ISSUE THREAD

**Issue by notkevin12** [ucsb-cs156-s22/team03-s22-6pm-1#24]
- [x] For admin user, there is a coloum that has a delete button for each row of the help request table.
- [x] By clicking on the delete button as an admin user, the corresponding row disappears and the corresponding entry in the database is deleted.
- [x] The new changes are updated to Heroku depolyment and works properly.
- [x] 100% test coverage and mutation coverage.

**Comment by hanzemeng** [comment]
- [ ] There is a delete column
- [ ] Press the delete

**Comment by hanzemeng** [comment]
- [ ] There is a coloum that has a delete button for each row of the help request table.
- [ ] By clicking on the delete button as an admin user, the corresponding row disappears and the corresponding entry in the database is deleted.
- [ ] The new changes are updated to Heroku depolyment and works properly.
- [ ] 100% test coverage and mutation coverage.
