### ISSUE TITLE
Add Delete Column to ReviewTable (if not already done)

### ISSUE THREAD

**Issue by SrijitBoinapally** [ucsb-cs156-s22/team03-s22-6pm-1#28]
- [x] Delete column appears in the Review page
- [x] Database deletes items with delete button
- [x] Full coverage, no eslint errors, passes Stryker
- [x] Works on Heroku QA

**Comment by tchang887** [comment]
- [ ] Delete column appears in the Review page
- [ ] Database deletes items with delete button
- [ ] Full coverage, no eslint errors, passes Stryker
- [ ] Works on Heroku QA
