### ISSUE TITLE
Add Recommendation menu to nav bar

### ISSUE THREAD

**Issue by notkevin12** [ucsb-cs156-s22/team03-s22-6pm-1#7]
- [x] Pulldown menu for Recommendations
- [x] Dropdown menu has List Recommendation
- [x] When 'List Recommendation' is clicked, opens a page in 'recommendation/lists'
- [x] Passes all tests on npm coverage/stryker
- [x] Works as expected on Heroku QA

**Comment by AadityaChannabasappa** [comment]
Mistake comment
